### ISSUE TITLE
Usage with react

### ISSUE THREAD

**Issue by asifkabani** [turkus/react-flying-objects#1]
Hi I am new and was wondering, can I use this with just react or it has to be react-native-web?

**Comment by turkus** [comment]
Hi, @asifkabani I'm so sorry for a delay, I didn't get notification. You can use it with just react.

**Comment by SaadBazaz** [comment]
It doesn't work with "just react". It demands that react-native-web be installed.

**Comment by turkus** [comment]
> It doesn't work with "just react". It demands that react-native-web be installed.

@SaadBazaz yes I agree. Small misunderstanding from my side.
